apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-deployment
spec:
  selector:
    matchLabels:
      type: discovery-app
  replicas: 2
  strategy:
    type: RollingUpdate       # 무중단 배포 방식
  minReadySeconds: 10
  template:
    metadata:
      labels:
        type: discovery-app
    spec:
      containers:
        - name: discovery-container
          image: [도커_이미지_이름]
          readlinessProbe:
            httpGet:
              path: /test/connect
              port: 6060
            initialDelaySeconds: 5    # 최초 Probe전의 지연 시간
            periodSeconds: 2          # Probe를 체크하는 시간 간격
            successThreshold: 3       # 성공 결과 수신 횟수
          ports:
            - containerPort: 6060
      terminationGracePeriodSeconds: 10   # 컨테이너가 강제 종료되기 전의 유예시간